Guessing Game/Controllers/AjaxController.cs
using Guessing_Game.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace Guessing_Game.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AjaxController : Controller
    {
        [Route("/Ajax")]
        public IActionResult Index()
        {
            

            return View();
        }

        [Route("/Ajax/People")]
        public IActionResult People()
        {
            PeopleViewModel model = new PeopleViewModel();

            return PartialView("_PersonList",model.people);
        }

        [HttpPost]
        [Route("/Ajax/{personID?}")]
        public IActionResult Index(string personID)
        {
            //PeopleViewModel model = new PeopleViewModel();

            int number = int.Parse(personID);

            

            if (PeopleList._list.Find(x => x.PersonId == number) != null)
            {
                Person queryperson = PeopleList._list.Find(x => x.PersonId == number);

                return PartialView("_PersonItem",queryperson);
            }


            return PartialView("_IdNotFound");
        }



        [HttpPost]
        [Route("/Ajax/Delete/{personID?}")]
        public IActionResult Delete(string personID)
        {
            

            int number = int.Parse(personID);



            if (PeopleList._list.Find(x => x.PersonId == number) != null)
            {
                Person queryperson = PeopleList._list.Find(x => x.PersonId == number);

                PeopleList._list.Remove(queryperson);

                return PartialView("_onSuccessDelete", queryperson);
            }


            return PartialView("_DeleteMessage");
        }



    }
}

Guessing Game/Controllers/CityController.cs
using Guessing_Game.Data;
using Guessing_Game.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace Guessing_Game.Controllers
{
    [Authorize(Roles= "Admin")]
    public class CityController : Controller
    {
        private readonly AppDbContext _appContext;
        public CityController(AppDbContext config)
        {
            _appContext = config;
        }
        public IActionResult Index()
        {
            List<City> listOfCities = _appContext.Cities.ToList();

            var countries  = _appContext.Countries.ToList();

            ViewBag.countries = countries;


            return View(listOfCities);


        }

        public IActionResult AddCity()
        {
            ViewBag.Countries = new SelectList(_appContext.Countries, "CountryName", "CountryName");

            return View();
        }


        [HttpPost]
        public IActionResult AddCity(string CityName, string CountryName)
        {
            Country countryToAdd = _appContext.Countries.FirstOrDefault(c => c.CountryName == CountryName);

           
            
                City city = new City()
                {
                    CityName = CityName,
                    CountryId = countryToAdd.CountryId, 
                    //Country = new Country() { CountryName = CountryName }
                };

                _appContext.Cities.Add(city);
                _appContext.SaveChanges();
                return RedirectToAction("Index");
         


            
        }


        public IActionResult Remove(City city)
        {
            City cityToRemove = _appContext.Cities.Find(city.CityId);


            _appContext.Cities.Remove(cityToRemove);
            _appContext.SaveChanges();
            return RedirectToAction("Index");


        }
    }
}

Guessing Game/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using Guessing_Game.Models;
using System;
using Microsoft.AspNetCore.Authorization;

namespace Guessing_Game.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DoctorController : Controller
    {
        [Route("/FeverCheck")]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [Route ("/FeverCheck")]
        public IActionResult TempCheck(int temp)
        {
            string result = Utility.CheckTemp(temp);
            ViewBag.Result = result;
            ViewBag.Temp = temp;


            return View();
        }
    }
}

Guessing Game/Controllers/RoleController.cs
using Guessing_Game.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace Guessing_Game.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
    
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<AppUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<AppUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }

        
        public IActionResult Index()
        {
            return View(_roleManager.Roles);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(string name)
        {
            IdentityResult result = await  _roleManager.CreateAsync(new IdentityRole { Name= name });

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View();
            
        }

        public IActionResult AddUserToRole()
        {
            ViewBag.Roles = new SelectList(_roleManager.Roles, "Name","Name");
            ViewBag.Users = new SelectList(_userManager.Users, "Id","UserName");
            return View();

        }

        [HttpPost]
        public async Task<IActionResult> AddUserToRole(string role, string user)
        {
            var currentUser = await _userManager.FindByIdAsync(user) ;
            IdentityResult result = await _userManager.AddToRoleAsync(currentUser, role);

            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View();

        }
    }
}

Guessing Game/Views/Shared/_CityItem.cshtml
@model Guessing_Game.Models.City



<div class="row">
    <div class="col-md-1">@Model.CityId</div>
    <div class="col-md-3">@Model.CityName</div>
    @*div class="col-md-2">@Html.ActionLink("Delete user", "RemoveUser","People", new {id = Model.PersonId})</div>*@
    <div class="col-md-2"><a asp-action="Remove" asp-controller="City" asp-route-cityId=@Model.CityId>Remove</a></div>
</div>

Guessing Game/Views/Shared/_DeleteMessage.cshtml
<h2>Person was not found</h2>

Guessing Game/Views/Shared/_IdNotFound.cshtml
<h2>No Id was found</h2>

Guessing Game/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    
    <link href="@Url.Content("~/bootstrap/css/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/main.css")" rel="stylesheet" type="text/css" />
    
    @RenderSection("Styles", false)
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>

        <header >
            <nav class="navbar navbar-expand-xxl navbar-dark bg-primary">
              <div class="container-fluid">
                <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Home" asp-action="Index" >
                    Logo
                    </a>
                <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav list-group">
                    @*<li class="nav-item ms-4">
                      <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Home" asp-action="About" >About</a>
                    </li>
                    <li class="nav-item ms-4 ">
                        
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Home" asp-action="Contact" >Contact</a>
                      
                    </li>
                    <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Home" asp-action="Projects" >Projects</a>
                      
                    </li>*@
                    @*<li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Doctor" asp-action="Index" >Check Temperature</a>
                      
                    </li>
                    <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="GuessingGame" asp-action="Index" >Guessing Game</a>
                      
                    </li>*@
                    @*if(User.IsInRole("Admin")){
                        <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Ajax" asp-action="Index" >Ajax</a>
                      
                    </li>
                    }*@
                    
                    <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="People" asp-action="Index" >People</a>
                      
                    </li>
                    <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="ReactPeople" asp-action="Index" > React People</a>
                      
                    </li>

                    @if(User.IsInRole("Admin")){
                        <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="City" asp-action="Index" >Cities</a>
                      
                    </li>
                    }
                    
                    @if(User.IsInRole("Admin")){
                        <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Country" asp-action="Index" >Countries</a>
                    </li>
                    }
                    
                    @if(User.IsInRole("Admin")){
                        <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Language" asp-action="Index" >Languages</a>
                    </li>
                    <li class="nav-item ms-4 ">    
                        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="Role" asp-action="Index" >Roles</a>
                    </li>

                    }
                    
                    <partial name=_LoginPartial />
                  </ul>
                </div>
              </div>
            </nav>
            
        </header>


        <main id="override" class="container main">
             @RenderBody()
             
        </main>
            
            


        <footer class="footer"> @DateTime.Now.ToShortDateString() -  Marek Piotrowski</footer>
    </div>
    
    <script src="~/bootstrap/js/bootstrap.min.js" language="javascript" type="text/javascript"></script>
    <script src="~/lib/jquery/jquery.min.js" language="javascript" type="text/javascript"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js" language="javascript" type="text/javascript"></script>
    
    <script src="~/main.js" language="javascript" type="text/javascript" defer></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Guessing Game/Views/Shared/_PersonItem.cshtml
@model Guessing_Game.Models.Person



<div class="row">
    <div class="col-md-1">@Model.PersonId</div>
    <div class="col-md-3">@Model.Name</div>
    <div class="col-md-3">@Model.PhoneNumber</div>
    <div class="col-md-2">@Model.CityId</div>
    @*<div class="col-md-2">@Model.PersonLanguages.Find(c => c.PersonId == Model.PersonId).Language.LanguageName</div>*@
    @*<div class="col-md-2">@((ViewBag.langs as List<Language>).Find(d => d.CountryId == item.CountryId).CountryName) </div>*@
    <div class="col-md-1"><a asp-action="Remove" asp-controller="People" asp-route-personId="@Model.PersonId">Remove</a></div>
</div>

Guessing Game/Views/Shared/_PersonList.cshtml
@model List<Guessing_Game.Models.Person>

<div class="row" >
    <div class="col-md-1">#</div>
    <div class="col-md-3">Name</div>
    <div class="col-md-3">City</div>
    <div class="col-md-3">Phone Number</div>
    <div class="col-md-2">Link to delete</div>
</div>
 <br />

@foreach(var item in Model){

    <div class="row">
        <div class="col-md-1">@item.Id</div>
        <div class="col-md-3">@item.Name</div>
        <div class="col-md-3">@item.City</div>
        <div class="col-md-3">@item.PhoneNumber</div>
        <div class="col-md-2">@Html.ActionLink("Delete user", "RemoveUser","People", new {id = @item.Id})</div>
        
        
    </div>

   
}

    

Guessing Game/Views/Shared/_onSuccessDelete.cshtml
@model Guessing_Game.Models.Person



<div class="row">
    <div class="col-md-3">Person with ID</div>
    <div class="col-md-3">@Model.PersonId</div>
    <div class="col-md-3">@Model.Name</div>
    <div class="col-md-3">Has been deleted</div>
</div>