Guessing Game/Controllers/GuessingGameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using Guessing_Game.Models;

namespace Guessing_Game.Controllers
{
    public class GuessingGameController : Controller
    {
        [Route("/GuessingGame")]
        public IActionResult Index()
        {
            Random random = new Random();
            int num = random.Next(1, 100);

            HttpContext.Session.SetString("GuessSession", num.ToString());
            ViewBag.Number = "Start game";

            ViewBag.Message = "Session has been set";



            return View();
        }

        [HttpPost]
        [Route("/GuessingGame")]
        public IActionResult Index(int number)
        {
            ViewBag.Session = HttpContext.Session.GetString("GuessSession");
            ViewBag.Validation = Utility.CheckNumber(number, ViewBag.Session);
            
            ViewBag.Number = Utility.ConvertNumberToString(number);

            

            return View();
            
        }
    }
}

Guessing Game/Views/GuessingGame/Index.cshtml
@using Guessing_Game.Models

@{
    ViewData["Title"] = "Index";
}

<h1>Guessing Game</h1>
<hr />
<p>A number between 1 - 100  has been generated!</p>
<p>Your job is to guess that number!</p>
<hr />

<form method="post" action="/GuessingGame">
    <label>Your number:</label>
    <input type="number" label="Your number" name="number" />
    <input type="submit" value="Check" />
</form>


@if(ViewBag.Number == ViewBag.Session)
{
    <h2>Congrats! You win!! Secret number was. @ViewBag.Session</h2>
    
        <a class="nav-link text-decoration-none text-light" aria-current="page" asp-controller="GuessingGame" asp-action="Index" >
            <button type="button" class="btn btn-warning"> Restart Game</button>
        </a>
}

@if(ViewBag.Number != ViewBag.Session)
{
    if(ViewBag.Number == "Start game")
    {
        <h4> Enter your number and start the game.</h4>
    }
    else
    {
        <h4>Keep guessing</h4>
        <h4>Your number was: @ViewBag.Number </h4>
        <h4>It is: @ViewBag.Validation </h4>
    }
    
}